### YamlMime:ManagedReference
items:
- uid: Songhay.Publications.DataAccess.EntityTypeConfigurations
  commentId: N:Songhay.Publications.DataAccess.EntityTypeConfigurations
  id: Songhay.Publications.DataAccess.EntityTypeConfigurations
  children:
  - Songhay.Publications.DataAccess.EntityTypeConfigurations.DocumentEntityTypeConfiguration
  - Songhay.Publications.DataAccess.EntityTypeConfigurations.ImageCandidateEntityTypeConfiguration
  - Songhay.Publications.DataAccess.EntityTypeConfigurations.IndexKeywordEntityTypeConfiguration
  - Songhay.Publications.DataAccess.EntityTypeConfigurations.IndexKeywordGroupEntityTypeConfiguration
  - Songhay.Publications.DataAccess.EntityTypeConfigurations.ResponsiveImageEntityTypeConfiguration
  - Songhay.Publications.DataAccess.EntityTypeConfigurations.SegmentEntityTypeConfiguration
  langs:
  - csharp
  - vb
  name: Songhay.Publications.DataAccess.EntityTypeConfigurations
  nameWithType: Songhay.Publications.DataAccess.EntityTypeConfigurations
  fullName: Songhay.Publications.DataAccess.EntityTypeConfigurations
  type: Namespace
  assemblies:
  - Songhay.Publications.DataAccess
references:
- uid: Songhay.Publications.DataAccess.EntityTypeConfigurations.DocumentEntityTypeConfiguration
  commentId: T:Songhay.Publications.DataAccess.EntityTypeConfigurations.DocumentEntityTypeConfiguration
  href: Songhay.Publications.DataAccess.EntityTypeConfigurations.DocumentEntityTypeConfiguration.html
  name: DocumentEntityTypeConfiguration
  nameWithType: DocumentEntityTypeConfiguration
  fullName: Songhay.Publications.DataAccess.EntityTypeConfigurations.DocumentEntityTypeConfiguration
- uid: Songhay.Publications.DataAccess.EntityTypeConfigurations.ImageCandidateEntityTypeConfiguration
  commentId: T:Songhay.Publications.DataAccess.EntityTypeConfigurations.ImageCandidateEntityTypeConfiguration
  href: Songhay.Publications.DataAccess.EntityTypeConfigurations.ImageCandidateEntityTypeConfiguration.html
  name: ImageCandidateEntityTypeConfiguration
  nameWithType: ImageCandidateEntityTypeConfiguration
  fullName: Songhay.Publications.DataAccess.EntityTypeConfigurations.ImageCandidateEntityTypeConfiguration
- uid: Songhay.Publications.DataAccess.EntityTypeConfigurations.IndexKeywordEntityTypeConfiguration
  commentId: T:Songhay.Publications.DataAccess.EntityTypeConfigurations.IndexKeywordEntityTypeConfiguration
  href: Songhay.Publications.DataAccess.EntityTypeConfigurations.IndexKeywordEntityTypeConfiguration.html
  name: IndexKeywordEntityTypeConfiguration
  nameWithType: IndexKeywordEntityTypeConfiguration
  fullName: Songhay.Publications.DataAccess.EntityTypeConfigurations.IndexKeywordEntityTypeConfiguration
- uid: Songhay.Publications.DataAccess.EntityTypeConfigurations.IndexKeywordGroupEntityTypeConfiguration
  commentId: T:Songhay.Publications.DataAccess.EntityTypeConfigurations.IndexKeywordGroupEntityTypeConfiguration
  href: Songhay.Publications.DataAccess.EntityTypeConfigurations.IndexKeywordGroupEntityTypeConfiguration.html
  name: IndexKeywordGroupEntityTypeConfiguration
  nameWithType: IndexKeywordGroupEntityTypeConfiguration
  fullName: Songhay.Publications.DataAccess.EntityTypeConfigurations.IndexKeywordGroupEntityTypeConfiguration
- uid: Songhay.Publications.DataAccess.EntityTypeConfigurations.ResponsiveImageEntityTypeConfiguration
  commentId: T:Songhay.Publications.DataAccess.EntityTypeConfigurations.ResponsiveImageEntityTypeConfiguration
  href: Songhay.Publications.DataAccess.EntityTypeConfigurations.ResponsiveImageEntityTypeConfiguration.html
  name: ResponsiveImageEntityTypeConfiguration
  nameWithType: ResponsiveImageEntityTypeConfiguration
  fullName: Songhay.Publications.DataAccess.EntityTypeConfigurations.ResponsiveImageEntityTypeConfiguration
- uid: Songhay.Publications.DataAccess.EntityTypeConfigurations.SegmentEntityTypeConfiguration
  commentId: T:Songhay.Publications.DataAccess.EntityTypeConfigurations.SegmentEntityTypeConfiguration
  href: Songhay.Publications.DataAccess.EntityTypeConfigurations.SegmentEntityTypeConfiguration.html
  name: SegmentEntityTypeConfiguration
  nameWithType: SegmentEntityTypeConfiguration
  fullName: Songhay.Publications.DataAccess.EntityTypeConfigurations.SegmentEntityTypeConfiguration
